#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
	python <<END
import sys

import psycopg2
import urllib.parse as urlparse
import os

url = urlparse.urlparse(os.environ['DATABASE_URL'])
dbname = url.path[1:]
user = url.username
password = url.password
host = url.hostname
port = url.port

try:
    psycopg2.connect(
        dbname=dbname,
        user=user,
        password=password,
        host=host,
        port=port
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
	echo >&2 'Waiting for PostgreSQL to become available...'
	sleep 1
done
echo >&2 'PostgreSQL is available'

exec "$@"
