name: Deploy

on:
  push:
    branches: [main]

jobs:
  update-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/gorel/github/discord_dicebot/
            git fetch
            CHANGED=$(git diff HEAD..origin/main -- requirements.txt compose/Dockerfile | wc -l)
            git pull
            if [ "$CHANGED" -gt "0" ]; then
              docker compose build
            fi
            sudo systemctl restart docker-compose@dicebot
