name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-stytch:
    runs-on: ubuntu-latest

    name: Run tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest
