name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test-stytch:
    runs-on: ubuntu-latest

    name: Run tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create coverage report
        env:
          STYTCH_PROJECT_ID: ""
          STYTCH_SECRET: ""
          WEB_SECRET_KEY: ""
          OPENAI_API_KEY: "FAKE_VALUE"
        run: |
          coverage run -m unittest
          coverage xml --omit="*test/*"

      - name: Get coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
